### ISSUE TITLE
Функция loginByRequest() не работает, если не передан токен взапросе

### ISSUE THREAD

**Issue by idoleg** [idoleg/jwt-auth#1]
Call to a member function getClaim() on boolean - FatalThrowableError in JwtGuard.php line 202

**Comment by idoleg** [comment]
error #2
"Uncaught InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in /home/vagrant/api-server/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:75\nStack trace:\n#0 /home/vagrant/api-server/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)\n#1 /home/vagrant/api-server/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)\n#2 /home/vagrant/api-server/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(83): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 0)\n#3 /home/vagrant/api-server/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Routing\\ResponseFactory->json(Array, 500)\n#4 /home/vagrant/api-server/app/Exceptions/Handler.php(70): Illuminate\\Support\\Facades\\Facade::__callStatic('json', Array)\n#5 /home/vagrant/api-server/vendor/laravel/framework/src/Illuminate/Foundation/Bootst"
